#! /bin/sh

xrandr --output DP-0 --mode 1920x1080 --rate 164 --primary --right-of HDMI-0 &

xset m 1 1 &
xset s off &     # Disable screen saver
xset -dpms &    # Disable DPMS (Energy Star) features

~/.config/polybar/launch.sh &

feh --randomize --bg-scale ~/.config/img/*

xsetroot -cursor_name left_ptr &

bspc monitor DP-0 -d 1 2 3 4 5 6 7 8 9 10
bspc monitor HDMI-0 -d Discord Spotify Random

bspc config border_width 2
bspc config window_gap 5

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a LibreWolf desktop="^4"
bspc rule -a firefox desktop="^4"
bspc rule -a discord desktop="^1"
bspc rule -a Spotify desktop="^2"
bspc rule -a steam desktop="^5"

pgrep -x sxhkd > /dev/null || sxhkd &

pgrep -x picom > /dev/null || picom &
pgrep -x dunst > /dev/null || dunst &

pgrep -x discord > /dev/null || discord &
pgrep -x spotify > /dev/null || spotify &
pgrep -x librewolf > /dev/null || librewolf &
pgrep -x steam > /dev/null || steam &
