#! /bin/sh

xrandr --output DP-0 --mode 1920x1080 --rate 164 --primary --right-of HDMI-0 &

xset m 1 1 &
xset s off &     # Disable screen saver
xset -dpms &    # Disable DPMS (Energy Star) features

sxhkd &

~/.config/polybar/launch.sh &

picom &
dunst &

feh --randomize --bg-scale ~/.config/img/*

xsetroot -cursor_name left_ptr &

bspc monitor DP-0 -d 1 2 3 4 5 6 7 8 9 10
bspc monitor HDMI-0 -d Discord Spotify Random

bspc config border_width 2
bspc config window_gap 12

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

discord &
while ! bspc query -N -n .window > /dev/null; do
    sleep 0.1 # Wait for the window to appear
done
bspc node -d 'Discord'

spotify &
while ! bspc query -N -n .window > /dev/null; do
    sleep 0.1 # Wait for the window to appear
done
bspc node -d 'Spotify'
