general {
	gaps_in = 4
	gaps_out = 4
	border_size = 1
	col.active_border = rgba(BB9AF7FF)
}

decoration {
	rounding = 5
	inactive_opacity = 0.9
}

animations {
	enabled = true

	animation = windows, 1, 1, default
	animation = windowsOut, 1, 1, default, popin 80%
	animation = border, 1, 1, default
	animation = borderangle, 1, 1, default
	animation = fade, 1, 1, default
	animation = workspaces, 1, 1, default
}

misc {
	force_default_wallpaper = 0
	disable_hyprland_logo = true
}
