# BACKGROUND
background {
    monitor =
    path = ~/.config/hypr/images/oneshot.png
    blur_passes = 2
    contrast = 1
    brightness = 0.5
    vibrancy = 0.2
    vibrancy_darkness = 0.2
}

# INPUT FIELD
input-field {
	fade_on_empty = false
	size = 320, 70
	rounding = 17
	dots_rounding = -2
	dots_spacing = 0.3
	placeholder_text = <i>Password</i>
	inner_color = rgb(65, 72, 104)
	outer_color = rgb(187, 154, 247)
	font_color = rgb(187, 154, 247)

	capslock_color = rgba(224, 175, 104, 255)
	fail_color = rgba(247, 118, 142, 255)
	check_color = rgba(125, 207, 255, 255)

  position = 0, -140
  halign = center
  valign = center
}

# DATE
label {
  text = cmd[update:1000] date +"%A, %B %d"
  color = rgba(187, 154, 247, 0.75)
  font_size = 50
  font_family = FiraMono Nerd Font Mono
  position = 0, 300
  halign = center
  valign = center
}

# TIME
label {
  text = cmd[update:1000] date +"%-H:%M"
  color = rgba(187, 154, 247, 0.75)
  font_size = 95
  font_family = FiraMono Nerd Font Mono
  position = 0, 100
  halign = center
  valign = center
}

# CURRENT SONG
label {
    monitor =
    text = cmd[update:1000] echo $(~/.config/hypr/scripts/whatsong.sh)
    color = rgba(255, 255, 255, 0.6)
    font_size = 18
    font_family = FiraMono Nerd Font Mono
    position = 0, 50
    halign = center
    valign = bottom
}
