set -sg terminal-overrides ",*:RGB"
set -g escape-time 0
set -g mouse on
set -g renumber-windows on
set -g repeat-time 1000

set -g base-index 1
set -g pane-base-index 1

setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

unbind r
bind r source-file ~/.tmux.conf

unbind C-b
set -g prefix C-s
bind C-s send-prefix

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

unbind v
unbind s
bind s split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"

unbind q
bind q kill-pane

unbind g
bind g display-popup -d "#{pane_current_path}" -w 90% -h 80% -E "lazygit"

set -g status-position top
set -g status-justify absolute-centre
set -g status-interval 1

set -g status-style bg="#201f35",fg="#1d1c31"

set -g status-left-length 40
set -g status-left ""

set -g status-right-length 80
set -g status-right ""

set -g message-style bg="#201f35",fg="#2ac3de"
set -g message-command-style bg="#201f35",fg="#2ac3de"

set -g window-status-current-style bg="#201f35",fg="#2ac3de",bold
set -g window-status-current-format " #I:#W#{?window_zoomed_flag,:z,} "

set -g window-status-style bg="#201f35",fg="#8A89a6"
set -g window-status-format " #I:#W "

set -g pane-border-style fg="#1d1c31"
set -g pane-active-border-style fg="#2ac3de"
set -g pane-border-lines heavy

set -g mode-style bg="#EAB575",fg="#201F35"
