unbind r
bind r source-file ~/.tmux.conf

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -g prefix C-s

set -g mouse on

setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind -n C-h select-pane -L
bind -n C-j select-pane -D
bind -n C-k select-pane -U
bind -n C-l select-pane -R

set -g base-index 1

unbind-key &
bind-key & kill-window

unbind-key z
bind-key z kill-window

unbind-key x
bind-key x kill-pane

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

run '~/.tmux/plugins/tpm/tpm'

##### Status Bar #####

# Place the status bar at the top
set -g status-position top
set -g status-justify absolute-centre

# Refresh interval
set -g status-interval 5

# Status bar colors
set -g status-style bg="#201F35",fg="#1D1C31"

# Left side
set -g status-left-length 40
set -g status-left "#[fg=#EAB575,bg=#201F35,bold] #S "

# Right side
set -g status-right-length 80
set -g status-right "#[fg=#EAB575,bg=#201F35]%d-%m-%Y #[fg=#1D1C31]|#[fg=#EAB575] %H:%M "

# Inactive windows (visible)
set -g window-status-style bg="#201F35",fg="#8A89A6"
set -g window-status-format " #I:#W "

# Active window
set -g window-status-current-style bg="#201F35",fg="#EAB575",bold
set -g window-status-current-format " #I:#W "

# Pane border colors
set -g pane-border-style fg="#1D1C31"
set -g pane-active-border-style fg="#EAB575"

# Message (command prompt) colors
set -g message-style bg="#201F35",fg="#EAB575"
set -g message-command-style bg="#201F35",fg="#EAB575"

# Mode (copy mode) colors
set -g mode-style bg="#EAB575",fg="#201F35"

# Clock style
set -g clock-mode-colour "#EAB575"
